name: CI Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [16.x]

      steps:
        - uses: actions/checkout@v3

        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.node-version }}
        - run: npm ci
        - run: npm run build --if-present

  deploy-main:
    runs-on: ubuntu-latest
    
    environment:
      name: main
      
    needs: build

    steps:
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "score-analysis-system-front"
          heroku_email: "score.analysis.sytem@gmail.com"
